/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FieldType from './FieldType';

/**
 * The AlchemyFieldType model module.
 * @module com.alterian.ja.model/AlchemyFieldType
 * @version 6.35.0
 */
class AlchemyFieldType {
    /**
     * Constructs a new <code>AlchemyFieldType</code>.
     * 
     * @alias module:com.alterian.ja.model/AlchemyFieldType
     */
    constructor() { 
        
        AlchemyFieldType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AlchemyFieldType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/AlchemyFieldType} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/AlchemyFieldType} The populated <code>AlchemyFieldType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlchemyFieldType();

            if (data.hasOwnProperty('ID')) {
                obj['ID'] = FieldType.constructFromObject(data['ID']);
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlchemyFieldType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlchemyFieldType</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.ja.model/FieldType} ID
 */
AlchemyFieldType.prototype['ID'] = undefined;

/**
 * Name of the field
 * @member {String} Name
 */
AlchemyFieldType.prototype['Name'] = undefined;






export default AlchemyFieldType;

