/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DatasourceAttribute from './DatasourceAttribute';

/**
 * The ALDataSourceColumn model module.
 * @module com.alterian.ja.model/ALDataSourceColumn
 * @version 6.35.0
 */
class ALDataSourceColumn {
    /**
     * Constructs a new <code>ALDataSourceColumn</code>.
     * Contains information about a database column.
     * @alias module:com.alterian.ja.model/ALDataSourceColumn
     */
    constructor() { 
        
        ALDataSourceColumn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ALDataSourceColumn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/ALDataSourceColumn} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/ALDataSourceColumn} The populated <code>ALDataSourceColumn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ALDataSourceColumn();

            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('NameEx')) {
                obj['NameEx'] = ApiClient.convertToType(data['NameEx'], 'String');
            }
            if (data.hasOwnProperty('Enabled')) {
                obj['Enabled'] = ApiClient.convertToType(data['Enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('Visible')) {
                obj['Visible'] = ApiClient.convertToType(data['Visible'], 'Boolean');
            }
            if (data.hasOwnProperty('AccessView')) {
                obj['AccessView'] = ApiClient.convertToType(data['AccessView'], 'Boolean');
            }
            if (data.hasOwnProperty('AccessModify')) {
                obj['AccessModify'] = ApiClient.convertToType(data['AccessModify'], 'Boolean');
            }
            if (data.hasOwnProperty('Attributes')) {
                obj['Attributes'] = ApiClient.convertToType(data['Attributes'], [DatasourceAttribute]);
            }
            if (data.hasOwnProperty('TableID')) {
                obj['TableID'] = ApiClient.convertToType(data['TableID'], 'Number');
            }
            if (data.hasOwnProperty('DatasourceId')) {
                obj['DatasourceId'] = ApiClient.convertToType(data['DatasourceId'], 'Number');
            }
            if (data.hasOwnProperty('NativeName')) {
                obj['NativeName'] = ApiClient.convertToType(data['NativeName'], 'String');
            }
            if (data.hasOwnProperty('AlchemyFieldTypeID')) {
                obj['AlchemyFieldTypeID'] = ApiClient.convertToType(data['AlchemyFieldTypeID'], 'Number');
            }
            if (data.hasOwnProperty('DatasourceTypeID')) {
                obj['DatasourceTypeID'] = ApiClient.convertToType(data['DatasourceTypeID'], 'Number');
            }
            if (data.hasOwnProperty('FullNativeName')) {
                obj['FullNativeName'] = ApiClient.convertToType(data['FullNativeName'], 'String');
            }
            if (data.hasOwnProperty('Precision')) {
                obj['Precision'] = ApiClient.convertToType(data['Precision'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ALDataSourceColumn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ALDataSourceColumn</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['NameEx'] && !(typeof data['NameEx'] === 'string' || data['NameEx'] instanceof String)) {
            throw new Error("Expected the field `NameEx` to be a primitive type in the JSON string but got " + data['NameEx']);
        }
        if (data['Attributes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Attributes'])) {
                throw new Error("Expected the field `Attributes` to be an array in the JSON data but got " + data['Attributes']);
            }
            // validate the optional field `Attributes` (array)
            for (const item of data['Attributes']) {
                DatasourceAttribute.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['NativeName'] && !(typeof data['NativeName'] === 'string' || data['NativeName'] instanceof String)) {
            throw new Error("Expected the field `NativeName` to be a primitive type in the JSON string but got " + data['NativeName']);
        }
        // ensure the json data is a string
        if (data['FullNativeName'] && !(typeof data['FullNativeName'] === 'string' || data['FullNativeName'] instanceof String)) {
            throw new Error("Expected the field `FullNativeName` to be a primitive type in the JSON string but got " + data['FullNativeName']);
        }

        return true;
    }


}



/**
 * Unique ID of the datasource
 * @member {Number} ID
 */
ALDataSourceColumn.prototype['ID'] = undefined;

/**
 * Name of the datasource [must be unique]
 * @member {String} Name
 */
ALDataSourceColumn.prototype['Name'] = undefined;

/**
 * Full name of this column, which includes in the datasource and the native name for the column in the pattern (datasource).[database].[table].[column]
 * @member {String} NameEx
 */
ALDataSourceColumn.prototype['NameEx'] = undefined;

/**
 * Whether or not this datasource is enabled
 * @member {Boolean} Enabled
 */
ALDataSourceColumn.prototype['Enabled'] = undefined;

/**
 * Whether or not this datasource is visible
 * @member {Boolean} Visible
 */
ALDataSourceColumn.prototype['Visible'] = undefined;

/**
 * Can the user view this datasource
 * @member {Boolean} AccessView
 */
ALDataSourceColumn.prototype['AccessView'] = undefined;

/**
 * Not currently used
 * @member {Boolean} AccessModify
 */
ALDataSourceColumn.prototype['AccessModify'] = undefined;

/**
 * Attributes for this datasource.  @see(DatasourceAttribute)
 * @member {Array.<module:com.alterian.ja.model/DatasourceAttribute>} Attributes
 */
ALDataSourceColumn.prototype['Attributes'] = undefined;

/**
 * 
 * @member {Number} TableID
 */
ALDataSourceColumn.prototype['TableID'] = undefined;

/**
 * 
 * @member {Number} DatasourceId
 */
ALDataSourceColumn.prototype['DatasourceId'] = undefined;

/**
 * The fully qualified name as used by the underlying datasource type.
 * @member {String} NativeName
 */
ALDataSourceColumn.prototype['NativeName'] = undefined;

/**
 * What type of data is contained within the column? Call @see(GetDatasourceFieldTypes) to fetch the mappings between this Type ID and name
 * @member {Number} AlchemyFieldTypeID
 */
ALDataSourceColumn.prototype['AlchemyFieldTypeID'] = undefined;

/**
 * What kind of datasource is this a column from?  See @see(GetDataSourceTypes) to fetch a list of the available datasource types.
 * @member {Number} DatasourceTypeID
 */
ALDataSourceColumn.prototype['DatasourceTypeID'] = undefined;

/**
 * The entire native name of this item -- usually includes database, table and column name
 * @member {String} FullNativeName
 */
ALDataSourceColumn.prototype['FullNativeName'] = undefined;

/**
 * If the column is a real type, this will be the precision, otherwise, it is meaningless
 * @member {Number} Precision
 */
ALDataSourceColumn.prototype['Precision'] = undefined;






export default ALDataSourceColumn;

