/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ALPermissionFlag from './ALPermissionFlag';
import PermissionSource from './PermissionSource';

/**
 * The ALPermission model module.
 * @module com.alterian.ja.model/ALPermission
 * @version 6.35.0
 */
class ALPermission {
    /**
     * Constructs a new <code>ALPermission</code>.
     * This represents a particular permission which is applied [either via inheritance or diretly] to a user.  A user may inherit permissions from folders or group membership.  Anything which has not been granted in some manner will be denied by default.
     * @alias module:com.alterian.ja.model/ALPermission
     */
    constructor() { 
        
        ALPermission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ALPermission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/ALPermission} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/ALPermission} The populated <code>ALPermission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ALPermission();

            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
            }
            if (data.hasOwnProperty('Value')) {
                obj['Value'] = ALPermissionFlag.constructFromObject(data['Value']);
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('Source')) {
                obj['Source'] = PermissionSource.constructFromObject(data['Source']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ALPermission</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ALPermission</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }

        return true;
    }


}



/**
 * The ID of the permission. (What right is being allowed or denied?)
 * @member {Number} ID
 */
ALPermission.prototype['ID'] = undefined;

/**
 * @member {module:com.alterian.ja.model/ALPermissionFlag} Value
 */
ALPermission.prototype['Value'] = undefined;

/**
 * The name of the permission
 * @member {String} Name
 */
ALPermission.prototype['Name'] = undefined;

/**
 * @member {module:com.alterian.ja.model/PermissionSource} Source
 */
ALPermission.prototype['Source'] = undefined;






export default ALPermission;

