/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AUTHSetLoginUserIdRequest model module.
 * @module com.alterian.ja.model/AUTHSetLoginUserIdRequest
 * @version 6.35.0
 */
class AUTHSetLoginUserIdRequest {
    /**
     * Constructs a new <code>AUTHSetLoginUserIdRequest</code>.
     * @alias module:com.alterian.ja.model/AUTHSetLoginUserIdRequest
     */
    constructor() { 
        
        AUTHSetLoginUserIdRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AUTHSetLoginUserIdRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/AUTHSetLoginUserIdRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/AUTHSetLoginUserIdRequest} The populated <code>AUTHSetLoginUserIdRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AUTHSetLoginUserIdRequest();

            if (data.hasOwnProperty('LoginId')) {
                obj['LoginId'] = ApiClient.convertToType(data['LoginId'], 'String');
            }
            if (data.hasOwnProperty('SiteId')) {
                obj['SiteId'] = ApiClient.convertToType(data['SiteId'], 'Number');
            }
            if (data.hasOwnProperty('UserId')) {
                obj['UserId'] = ApiClient.convertToType(data['UserId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AUTHSetLoginUserIdRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AUTHSetLoginUserIdRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['LoginId'] && !(typeof data['LoginId'] === 'string' || data['LoginId'] instanceof String)) {
            throw new Error("Expected the field `LoginId` to be a primitive type in the JSON string but got " + data['LoginId']);
        }

        return true;
    }


}



/**
 * Id of the login
 * @member {String} LoginId
 */
AUTHSetLoginUserIdRequest.prototype['LoginId'] = undefined;

/**
 * Id of the CM Site (typically 1)
 * @member {Number} SiteId
 */
AUTHSetLoginUserIdRequest.prototype['SiteId'] = undefined;

/**
 * User Id to associate with the login.  Pass NULL to disassociate the login with a user.
 * @member {Number} UserId
 */
AUTHSetLoginUserIdRequest.prototype['UserId'] = undefined;






export default AUTHSetLoginUserIdRequest;

