/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AUTHUpdateLoginRequest model module.
 * @module com.alterian.ja.model/AUTHUpdateLoginRequest
 * @version 6.35.0
 */
class AUTHUpdateLoginRequest {
    /**
     * Constructs a new <code>AUTHUpdateLoginRequest</code>.
     * @alias module:com.alterian.ja.model/AUTHUpdateLoginRequest
     */
    constructor() { 
        
        AUTHUpdateLoginRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AUTHUpdateLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/AUTHUpdateLoginRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/AUTHUpdateLoginRequest} The populated <code>AUTHUpdateLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AUTHUpdateLoginRequest();

            if (data.hasOwnProperty('ExternalAuthentication')) {
                obj['ExternalAuthentication'] = ApiClient.convertToType(data['ExternalAuthentication'], 'Boolean');
            }
            if (data.hasOwnProperty('LoginId')) {
                obj['LoginId'] = ApiClient.convertToType(data['LoginId'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('NewPassword')) {
                obj['NewPassword'] = ApiClient.convertToType(data['NewPassword'], 'String');
            }
            if (data.hasOwnProperty('SiteId')) {
                obj['SiteId'] = ApiClient.convertToType(data['SiteId'], 'Number');
            }
            if (data.hasOwnProperty('UserId')) {
                obj['UserId'] = ApiClient.convertToType(data['UserId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AUTHUpdateLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AUTHUpdateLoginRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['LoginId'] && !(typeof data['LoginId'] === 'string' || data['LoginId'] instanceof String)) {
            throw new Error("Expected the field `LoginId` to be a primitive type in the JSON string but got " + data['LoginId']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['NewPassword'] && !(typeof data['NewPassword'] === 'string' || data['NewPassword'] instanceof String)) {
            throw new Error("Expected the field `NewPassword` to be a primitive type in the JSON string but got " + data['NewPassword']);
        }

        return true;
    }


}



/**
 * True if you want this login to use external authentication [NT, SAML]
 * @member {Boolean} ExternalAuthentication
 */
AUTHUpdateLoginRequest.prototype['ExternalAuthentication'] = undefined;

/**
 * Id of the login
 * @member {String} LoginId
 */
AUTHUpdateLoginRequest.prototype['LoginId'] = undefined;

/**
 * Login name
 * @member {String} Name
 */
AUTHUpdateLoginRequest.prototype['Name'] = undefined;

/**
 * If you want to change the password, provide it here.  If ExternalAuth is true, this is ignored.  It must pass the password complexity rules.
 * @member {String} NewPassword
 */
AUTHUpdateLoginRequest.prototype['NewPassword'] = undefined;

/**
 * Id of the CM Site (typically 1)
 * @member {Number} SiteId
 */
AUTHUpdateLoginRequest.prototype['SiteId'] = undefined;

/**
 * User Id to associate with the login.  Pass NULL to disassociate the login with a user.
 * @member {Number} UserId
 */
AUTHUpdateLoginRequest.prototype['UserId'] = undefined;






export default AUTHUpdateLoginRequest;

