/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ColumnPublishedTransform model module.
 * @module com.alterian.ja.model/ColumnPublishedTransform
 * @version 6.35.0
 */
class ColumnPublishedTransform {
    /**
     * Constructs a new <code>ColumnPublishedTransform</code>.
     * 
     * @alias module:com.alterian.ja.model/ColumnPublishedTransform
     */
    constructor() { 
        
        ColumnPublishedTransform.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ColumnPublishedTransform</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/ColumnPublishedTransform} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/ColumnPublishedTransform} The populated <code>ColumnPublishedTransform</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ColumnPublishedTransform();

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
            }
            if (data.hasOwnProperty('EventStreamName')) {
                obj['EventStreamName'] = ApiClient.convertToType(data['EventStreamName'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('IsSystem')) {
                obj['IsSystem'] = ApiClient.convertToType(data['IsSystem'], 'Boolean');
            }
            if (data.hasOwnProperty('Version')) {
                obj['Version'] = ApiClient.convertToType(data['Version'], 'Number');
            }
            if (data.hasOwnProperty('Alias')) {
                obj['Alias'] = ApiClient.convertToType(data['Alias'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ColumnPublishedTransform</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ColumnPublishedTransform</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['EventStreamName'] && !(typeof data['EventStreamName'] === 'string' || data['EventStreamName'] instanceof String)) {
            throw new Error("Expected the field `EventStreamName` to be a primitive type in the JSON string but got " + data['EventStreamName']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['Alias'] && !(typeof data['Alias'] === 'string' || data['Alias'] instanceof String)) {
            throw new Error("Expected the field `Alias` to be a primitive type in the JSON string but got " + data['Alias']);
        }

        return true;
    }


}



/**
 * Id of the column to which the transform has been published
 * @member {Number} Id
 */
ColumnPublishedTransform.prototype['Id'] = undefined;

/**
 * Name of the event stream (client-target-queuename) to which the column belongs
 * @member {String} EventStreamName
 */
ColumnPublishedTransform.prototype['EventStreamName'] = undefined;

/**
 * Name of the column to which the transform has been published
 * @member {String} Name
 */
ColumnPublishedTransform.prototype['Name'] = undefined;

/**
 * Flag indicating whether the column represents a system column or a custom column (e.g. a customer attribute)
 * @member {Boolean} IsSystem
 */
ColumnPublishedTransform.prototype['IsSystem'] = undefined;

/**
 * Version of the transform that was published against the column
 * @member {Number} Version
 */
ColumnPublishedTransform.prototype['Version'] = undefined;

/**
 * Alias associated with the transform when it was published
 * @member {String} Alias
 */
ColumnPublishedTransform.prototype['Alias'] = undefined;






export default ColumnPublishedTransform;

