/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateStaticTokenRequest model module.
 * @module com.alterian.ja.model/CreateStaticTokenRequest
 * @version 6.35.0
 */
class CreateStaticTokenRequest {
    /**
     * Constructs a new <code>CreateStaticTokenRequest</code>.
     * @alias module:com.alterian.ja.model/CreateStaticTokenRequest
     */
    constructor() { 
        
        CreateStaticTokenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateStaticTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/CreateStaticTokenRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/CreateStaticTokenRequest} The populated <code>CreateStaticTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateStaticTokenRequest();

            if (data.hasOwnProperty('ClientID')) {
                obj['ClientID'] = ApiClient.convertToType(data['ClientID'], 'Number');
            }
            if (data.hasOwnProperty('UserID')) {
                obj['UserID'] = ApiClient.convertToType(data['UserID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateStaticTokenRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateStaticTokenRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * ClientID to which the new static token should be associated.  If you have an SA token, you must provide this parameter.  If you have a regular token, this parameter is ignored and the clientID of your token is used instead
 * @member {Number} ClientID
 */
CreateStaticTokenRequest.prototype['ClientID'] = undefined;

/**
 * UserID to which the new static token should be associated
 * @member {Number} UserID
 */
CreateStaticTokenRequest.prototype['UserID'] = undefined;






export default CreateStaticTokenRequest;

