/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BusinessGoal from './BusinessGoal';

/**
 * The CreateBusinessGoalRequest model module.
 * @module com.alterian.ja.model/CreateBusinessGoalRequest
 * @version 6.35.0
 */
class CreateBusinessGoalRequest {
    /**
     * Constructs a new <code>CreateBusinessGoalRequest</code>.
     * @alias module:com.alterian.ja.model/CreateBusinessGoalRequest
     */
    constructor() { 
        
        CreateBusinessGoalRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateBusinessGoalRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/CreateBusinessGoalRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/CreateBusinessGoalRequest} The populated <code>CreateBusinessGoalRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBusinessGoalRequest();

            if (data.hasOwnProperty('BusinessGoal')) {
                obj['BusinessGoal'] = BusinessGoal.constructFromObject(data['BusinessGoal']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBusinessGoalRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBusinessGoalRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `BusinessGoal`
        if (data['BusinessGoal']) { // data not null
          BusinessGoal.validateJSON(data['BusinessGoal']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.ja.model/BusinessGoal} BusinessGoal
 */
CreateBusinessGoalRequest.prototype['BusinessGoal'] = undefined;






export default CreateBusinessGoalRequest;

