/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateClientSetRequest model module.
 * @module com.alterian.ja.model/CreateClientSetRequest
 * @version 6.35.0
 */
class CreateClientSetRequest {
    /**
     * Constructs a new <code>CreateClientSetRequest</code>.
     * @alias module:com.alterian.ja.model/CreateClientSetRequest
     */
    constructor() { 
        
        CreateClientSetRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateClientSetRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/CreateClientSetRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/CreateClientSetRequest} The populated <code>CreateClientSetRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateClientSetRequest();

            if (data.hasOwnProperty('ClientSetName')) {
                obj['ClientSetName'] = ApiClient.convertToType(data['ClientSetName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateClientSetRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateClientSetRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ClientSetName'] && !(typeof data['ClientSetName'] === 'string' || data['ClientSetName'] instanceof String)) {
            throw new Error("Expected the field `ClientSetName` to be a primitive type in the JSON string but got " + data['ClientSetName']);
        }

        return true;
    }


}



/**
 * The name of the new clientset. The method will fail if another clientset already exists with this name.
 * @member {String} ClientSetName
 */
CreateClientSetRequest.prototype['ClientSetName'] = undefined;






export default CreateClientSetRequest;

