/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateEMSessionRequest model module.
 * @module com.alterian.ja.model/CreateEMSessionRequest
 * @version 6.35.0
 */
class CreateEMSessionRequest {
    /**
     * Constructs a new <code>CreateEMSessionRequest</code>.
     * @alias module:com.alterian.ja.model/CreateEMSessionRequest
     */
    constructor() { 
        
        CreateEMSessionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateEMSessionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/CreateEMSessionRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/CreateEMSessionRequest} The populated <code>CreateEMSessionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateEMSessionRequest();

            if (data.hasOwnProperty('AuthToken')) {
                obj['AuthToken'] = ApiClient.convertToType(data['AuthToken'], 'String');
            }
            if (data.hasOwnProperty('EMMappingId')) {
                obj['EMMappingId'] = ApiClient.convertToType(data['EMMappingId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateEMSessionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateEMSessionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['AuthToken'] && !(typeof data['AuthToken'] === 'string' || data['AuthToken'] instanceof String)) {
            throw new Error("Expected the field `AuthToken` to be a primitive type in the JSON string but got " + data['AuthToken']);
        }

        return true;
    }


}



/**
 * A valid auth token must be provided.
 * @member {String} AuthToken
 */
CreateEMSessionRequest.prototype['AuthToken'] = undefined;

/**
 * @see(EMMapping) Id which can be obtained from a call to @see(GetEMMappings)
 * @member {Number} EMMappingId
 */
CreateEMSessionRequest.prototype['EMMappingId'] = undefined;






export default CreateEMSessionRequest;

