/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteTransformRequest model module.
 * @module com.alterian.ja.model/DeleteTransformRequest
 * @version 6.35.0
 */
class DeleteTransformRequest {
    /**
     * Constructs a new <code>DeleteTransformRequest</code>.
     * @alias module:com.alterian.ja.model/DeleteTransformRequest
     */
    constructor() { 
        
        DeleteTransformRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteTransformRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/DeleteTransformRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/DeleteTransformRequest} The populated <code>DeleteTransformRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteTransformRequest();

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteTransformRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteTransformRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * ID of the list
 * @member {Number} Id
 */
DeleteTransformRequest.prototype['Id'] = undefined;






export default DeleteTransformRequest;

