/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeletePersonaRequest model module.
 * @module com.alterian.ja.model/DeletePersonaRequest
 * @version 6.35.0
 */
class DeletePersonaRequest {
    /**
     * Constructs a new <code>DeletePersonaRequest</code>.
     * @alias module:com.alterian.ja.model/DeletePersonaRequest
     */
    constructor() { 
        
        DeletePersonaRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeletePersonaRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/DeletePersonaRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/DeletePersonaRequest} The populated <code>DeletePersonaRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeletePersonaRequest();

            if (data.hasOwnProperty('PersonaId')) {
                obj['PersonaId'] = ApiClient.convertToType(data['PersonaId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeletePersonaRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeletePersonaRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Id of the persona to delete
 * @member {Number} PersonaId
 */
DeletePersonaRequest.prototype['PersonaId'] = undefined;






export default DeletePersonaRequest;

