/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteOpportunityRequest model module.
 * @module com.alterian.ja.model/DeleteOpportunityRequest
 * @version 6.35.0
 */
class DeleteOpportunityRequest {
    /**
     * Constructs a new <code>DeleteOpportunityRequest</code>.
     * @alias module:com.alterian.ja.model/DeleteOpportunityRequest
     */
    constructor() { 
        
        DeleteOpportunityRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteOpportunityRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/DeleteOpportunityRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/DeleteOpportunityRequest} The populated <code>DeleteOpportunityRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteOpportunityRequest();

            if (data.hasOwnProperty('OpportunityId')) {
                obj['OpportunityId'] = ApiClient.convertToType(data['OpportunityId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteOpportunityRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteOpportunityRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Id of the Opportunity to delete.
 * @member {Number} OpportunityId
 */
DeleteOpportunityRequest.prototype['OpportunityId'] = undefined;






export default DeleteOpportunityRequest;

