/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DiscreteValueData model module.
 * @module com.alterian.ja.model/DiscreteValueData
 * @version 6.35.0
 */
class DiscreteValueData {
    /**
     * Constructs a new <code>DiscreteValueData</code>.
     * 
     * @alias module:com.alterian.ja.model/DiscreteValueData
     */
    constructor() { 
        
        DiscreteValueData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DiscreteValueData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/DiscreteValueData} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/DiscreteValueData} The populated <code>DiscreteValueData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DiscreteValueData();

            if (data.hasOwnProperty('Labels')) {
                obj['Labels'] = ApiClient.convertToType(data['Labels'], ['String']);
            }
            if (data.hasOwnProperty('Frequencies')) {
                obj['Frequencies'] = ApiClient.convertToType(data['Frequencies'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DiscreteValueData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DiscreteValueData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['Labels'])) {
            throw new Error("Expected the field `Labels` to be an array in the JSON data but got " + data['Labels']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['Frequencies'])) {
            throw new Error("Expected the field `Frequencies` to be an array in the JSON data but got " + data['Frequencies']);
        }

        return true;
    }


}



/**
 * 
 * @member {Array.<String>} Labels
 */
DiscreteValueData.prototype['Labels'] = undefined;

/**
 * 
 * @member {Array.<Number>} Frequencies
 */
DiscreteValueData.prototype['Frequencies'] = undefined;






export default DiscreteValueData;

