/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DMFieldType.
* @enum {}
* @readonly
*/
export default class DMFieldType {
    
        /**
         * value: 1
         * @const
         */
        "DMFT_EMAIL" = 1;

    
        /**
         * value: 2
         * @const
         */
        "DMFT_STRING" = 2;

    
        /**
         * value: 3
         * @const
         */
        "DMFT_TEXT" = 3;

    
        /**
         * value: 4
         * @const
         */
        "DMFT_NUMERIC" = 4;

    
        /**
         * value: 5
         * @const
         */
        "DMFT_DATE" = 5;

    
        /**
         * value: 6
         * @const
         */
        "DMFT_BOOLEAN" = 6;

    
        /**
         * value: 7
         * @const
         */
        "DMFT_DECIMAL" = 7;

    
        /**
         * value: 8
         * @const
         */
        "DMFT_UNICODE" = 8;

    
        /**
         * value: 9
         * @const
         */
        "DMFT_PREFERENCE" = 9;

    

    /**
    * Returns a <code>DMFieldType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.alterian.ja.model/DMFieldType} The enum <code>DMFieldType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

