/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DMInboundEventForward from './DMInboundEventForward';

/**
 * The DMInboundAddress model module.
 * @module com.alterian.ja.model/DMInboundAddress
 * @version 6.35.0
 */
class DMInboundAddress {
    /**
     * Constructs a new <code>DMInboundAddress</code>.
     * 
     * @alias module:com.alterian.ja.model/DMInboundAddress
     */
    constructor() { 
        
        DMInboundAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DMInboundAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/DMInboundAddress} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/DMInboundAddress} The populated <code>DMInboundAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DMInboundAddress();

            if (data.hasOwnProperty('DeployAccess')) {
                obj['DeployAccess'] = ApiClient.convertToType(data['DeployAccess'], 'Boolean');
            }
            if (data.hasOwnProperty('Email')) {
                obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
            }
            if (data.hasOwnProperty('ForwardEvents')) {
                obj['ForwardEvents'] = ApiClient.convertToType(data['ForwardEvents'], [DMInboundEventForward]);
            }
            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
            }
            if (data.hasOwnProperty('ModifyAccess')) {
                obj['ModifyAccess'] = ApiClient.convertToType(data['ModifyAccess'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DMInboundAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DMInboundAddress</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Email'] && !(typeof data['Email'] === 'string' || data['Email'] instanceof String)) {
            throw new Error("Expected the field `Email` to be a primitive type in the JSON string but got " + data['Email']);
        }
        if (data['ForwardEvents']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ForwardEvents'])) {
                throw new Error("Expected the field `ForwardEvents` to be an array in the JSON data but got " + data['ForwardEvents']);
            }
            // validate the optional field `ForwardEvents` (array)
            for (const item of data['ForwardEvents']) {
                DMInboundEventForward.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * 
 * @member {Boolean} DeployAccess
 */
DMInboundAddress.prototype['DeployAccess'] = undefined;

/**
 * 
 * @member {String} Email
 */
DMInboundAddress.prototype['Email'] = undefined;

/**
 * 
 * @member {Array.<module:com.alterian.ja.model/DMInboundEventForward>} ForwardEvents
 */
DMInboundAddress.prototype['ForwardEvents'] = undefined;

/**
 * 
 * @member {Number} ID
 */
DMInboundAddress.prototype['ID'] = undefined;

/**
 * 
 * @member {Boolean} ModifyAccess
 */
DMInboundAddress.prototype['ModifyAccess'] = undefined;






export default DMInboundAddress;

