/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EMDocumentType.
* @enum {}
* @readonly
*/
export default class EMDocumentType {
    
        /**
         * value: 0
         * @const
         */
        "EMDT_Campaign" = 0;

    
        /**
         * value: 1
         * @const
         */
        "EMDT_Email" = 1;

    
        /**
         * value: 2
         * @const
         */
        "EMDT_Webpage" = 2;

    
        /**
         * value: 3
         * @const
         */
        "EMDT_Flow" = 3;

    
        /**
         * value: 4
         * @const
         */
        "EMDT_Deployment" = 4;

    

    /**
    * Returns a <code>EMDocumentType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.alterian.ja.model/EMDocumentType} The enum <code>EMDocumentType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

