/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EMGetClientSetsRequest model module.
 * @module com.alterian.ja.model/EMGetClientSetsRequest
 * @version 6.35.0
 */
class EMGetClientSetsRequest {
    /**
     * Constructs a new <code>EMGetClientSetsRequest</code>.
     * @alias module:com.alterian.ja.model/EMGetClientSetsRequest
     */
    constructor() { 
        
        EMGetClientSetsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EMGetClientSetsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/EMGetClientSetsRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/EMGetClientSetsRequest} The populated <code>EMGetClientSetsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EMGetClientSetsRequest();

            if (data.hasOwnProperty('EMSiteId')) {
                obj['EMSiteId'] = ApiClient.convertToType(data['EMSiteId'], 'Number');
            }
            if (data.hasOwnProperty('EMToken')) {
                obj['EMToken'] = ApiClient.convertToType(data['EMToken'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EMGetClientSetsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EMGetClientSetsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['EMToken'] && !(typeof data['EMToken'] === 'string' || data['EMToken'] instanceof String)) {
            throw new Error("Expected the field `EMToken` to be a primitive type in the JSON string but got " + data['EMToken']);
        }

        return true;
    }


}



/**
 * EM Site ID obtained from @see(GetEMMappings) or @see(GetEMMapping)
 * @member {Number} EMSiteId
 */
EMGetClientSetsRequest.prototype['EMSiteId'] = undefined;

/**
 * A valid EM token obtained via @see(EM_Authenticate).  Token MUST be an SA token.
 * @member {String} EMToken
 */
EMGetClientSetsRequest.prototype['EMToken'] = undefined;






export default EMGetClientSetsRequest;

