/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APICursor from './APICursor';

/**
 * The EMGetCreativesRequest model module.
 * @module com.alterian.ja.model/EMGetCreativesRequest
 * @version 6.35.0
 */
class EMGetCreativesRequest {
    /**
     * Constructs a new <code>EMGetCreativesRequest</code>.
     * @alias module:com.alterian.ja.model/EMGetCreativesRequest
     */
    constructor() { 
        
        EMGetCreativesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EMGetCreativesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/EMGetCreativesRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/EMGetCreativesRequest} The populated <code>EMGetCreativesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EMGetCreativesRequest();

            if (data.hasOwnProperty('CategoryId')) {
                obj['CategoryId'] = ApiClient.convertToType(data['CategoryId'], 'Number');
            }
            if (data.hasOwnProperty('CreatedByUserId')) {
                obj['CreatedByUserId'] = ApiClient.convertToType(data['CreatedByUserId'], 'Number');
            }
            if (data.hasOwnProperty('CreativeName')) {
                obj['CreativeName'] = ApiClient.convertToType(data['CreativeName'], 'String');
            }
            if (data.hasOwnProperty('Cursor')) {
                obj['Cursor'] = APICursor.constructFromObject(data['Cursor']);
            }
            if (data.hasOwnProperty('EMMappingId')) {
                obj['EMMappingId'] = ApiClient.convertToType(data['EMMappingId'], 'Number');
            }
            if (data.hasOwnProperty('ModifiedUtcEndDate')) {
                obj['ModifiedUtcEndDate'] = ApiClient.convertToType(data['ModifiedUtcEndDate'], 'Date');
            }
            if (data.hasOwnProperty('ModifiedUtcStartDate')) {
                obj['ModifiedUtcStartDate'] = ApiClient.convertToType(data['ModifiedUtcStartDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EMGetCreativesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EMGetCreativesRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['CreativeName'] && !(typeof data['CreativeName'] === 'string' || data['CreativeName'] instanceof String)) {
            throw new Error("Expected the field `CreativeName` to be a primitive type in the JSON string but got " + data['CreativeName']);
        }
        // validate the optional field `Cursor`
        if (data['Cursor']) { // data not null
          APICursor.validateJSON(data['Cursor']);
        }

        return true;
    }


}



/**
 * EM 'folder' to restrict results to selected category
 * @member {Number} CategoryId
 */
EMGetCreativesRequest.prototype['CategoryId'] = undefined;

/**
 * Created by user id, used for filtering
 * @member {Number} CreatedByUserId
 */
EMGetCreativesRequest.prototype['CreatedByUserId'] = undefined;

/**
 * All or partial value for creative name, used for filtering
 * @member {String} CreativeName
 */
EMGetCreativesRequest.prototype['CreativeName'] = undefined;

/**
 * @member {module:com.alterian.ja.model/APICursor} Cursor
 */
EMGetCreativesRequest.prototype['Cursor'] = undefined;

/**
 * Mapping Id to use for EM connection
 * @member {Number} EMMappingId
 */
EMGetCreativesRequest.prototype['EMMappingId'] = undefined;

/**
 * Upper range for modified start date filter
 * @member {Date} ModifiedUtcEndDate
 */
EMGetCreativesRequest.prototype['ModifiedUtcEndDate'] = undefined;

/**
 * Lower range for modified start date filter
 * @member {Date} ModifiedUtcStartDate
 */
EMGetCreativesRequest.prototype['ModifiedUtcStartDate'] = undefined;






export default EMGetCreativesRequest;

