/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EMPauseDeploymentRequest model module.
 * @module com.alterian.ja.model/EMPauseDeploymentRequest
 * @version 6.35.0
 */
class EMPauseDeploymentRequest {
    /**
     * Constructs a new <code>EMPauseDeploymentRequest</code>.
     * @alias module:com.alterian.ja.model/EMPauseDeploymentRequest
     */
    constructor() { 
        
        EMPauseDeploymentRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EMPauseDeploymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/EMPauseDeploymentRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/EMPauseDeploymentRequest} The populated <code>EMPauseDeploymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EMPauseDeploymentRequest();

            if (data.hasOwnProperty('DeploymentId')) {
                obj['DeploymentId'] = ApiClient.convertToType(data['DeploymentId'], 'Number');
            }
            if (data.hasOwnProperty('EMMappingId')) {
                obj['EMMappingId'] = ApiClient.convertToType(data['EMMappingId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EMPauseDeploymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EMPauseDeploymentRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Deployment Id to pause
 * @member {Number} DeploymentId
 */
EMPauseDeploymentRequest.prototype['DeploymentId'] = undefined;

/**
 * Mapping Id to use for EM connection
 * @member {Number} EMMappingId
 */
EMPauseDeploymentRequest.prototype['EMMappingId'] = undefined;






export default EMPauseDeploymentRequest;

