/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventStreamCustomerField model module.
 * @module com.alterian.ja.model/EventStreamCustomerField
 * @version 6.35.0
 */
class EventStreamCustomerField {
    /**
     * Constructs a new <code>EventStreamCustomerField</code>.
     * 
     * @alias module:com.alterian.ja.model/EventStreamCustomerField
     */
    constructor() { 
        
        EventStreamCustomerField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventStreamCustomerField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/EventStreamCustomerField} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/EventStreamCustomerField} The populated <code>EventStreamCustomerField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventStreamCustomerField();

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('DataType')) {
                obj['DataType'] = ApiClient.convertToType(data['DataType'], 'String');
            }
            if (data.hasOwnProperty('Width')) {
                obj['Width'] = ApiClient.convertToType(data['Width'], 'Number');
            }
            if (data.hasOwnProperty('Precision')) {
                obj['Precision'] = ApiClient.convertToType(data['Precision'], 'Number');
            }
            if (data.hasOwnProperty('IsSankey')) {
                obj['IsSankey'] = ApiClient.convertToType(data['IsSankey'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventStreamCustomerField</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventStreamCustomerField</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['DataType'] && !(typeof data['DataType'] === 'string' || data['DataType'] instanceof String)) {
            throw new Error("Expected the field `DataType` to be a primitive type in the JSON string but got " + data['DataType']);
        }

        return true;
    }


}



/**
 * Field name as it should appear in the UI and Engine repository
 * @member {String} Name
 */
EventStreamCustomerField.prototype['Name'] = undefined;

/**
 * Allowed values: unicode, text, datetime, date, integer, int64, real
 * @member {String} DataType
 */
EventStreamCustomerField.prototype['DataType'] = undefined;

/**
 * Only required for unicode and text types
 * @member {Number} Width
 */
EventStreamCustomerField.prototype['Width'] = undefined;

/**
 * Only required for real data type
 * @member {Number} Precision
 */
EventStreamCustomerField.prototype['Precision'] = undefined;

/**
 * Flag inidicating whether to display the customer field as a Sankey filter
 * @member {Boolean} IsSankey
 */
EventStreamCustomerField.prototype['IsSankey'] = undefined;






export default EventStreamCustomerField;

