/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APICursor from './APICursor';

/**
 * The GetDatasourceTablesRequest model module.
 * @module com.alterian.ja.model/GetDatasourceTablesRequest
 * @version 6.35.0
 */
class GetDatasourceTablesRequest {
    /**
     * Constructs a new <code>GetDatasourceTablesRequest</code>.
     * @alias module:com.alterian.ja.model/GetDatasourceTablesRequest
     */
    constructor() { 
        
        GetDatasourceTablesRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetDatasourceTablesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/GetDatasourceTablesRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/GetDatasourceTablesRequest} The populated <code>GetDatasourceTablesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDatasourceTablesRequest();

            if (data.hasOwnProperty('Cursor')) {
                obj['Cursor'] = APICursor.constructFromObject(data['Cursor']);
            }
            if (data.hasOwnProperty('DatabaseID')) {
                obj['DatabaseID'] = ApiClient.convertToType(data['DatabaseID'], 'Number');
            }
            if (data.hasOwnProperty('IncludeDisabled')) {
                obj['IncludeDisabled'] = ApiClient.convertToType(data['IncludeDisabled'], 'Boolean');
            }
            if (data.hasOwnProperty('IncludeInvisible')) {
                obj['IncludeInvisible'] = ApiClient.convertToType(data['IncludeInvisible'], 'Boolean');
            }
            if (data.hasOwnProperty('IncludeJoins')) {
                obj['IncludeJoins'] = ApiClient.convertToType(data['IncludeJoins'], 'Boolean');
            }
            if (data.hasOwnProperty('IncludeLinks')) {
                obj['IncludeLinks'] = ApiClient.convertToType(data['IncludeLinks'], 'Boolean');
            }
            if (data.hasOwnProperty('MinimalResults')) {
                obj['MinimalResults'] = ApiClient.convertToType(data['MinimalResults'], 'Boolean');
            }
            if (data.hasOwnProperty('NameFilter')) {
                obj['NameFilter'] = ApiClient.convertToType(data['NameFilter'], 'String');
            }
            if (data.hasOwnProperty('ResolutionTableID')) {
                obj['ResolutionTableID'] = ApiClient.convertToType(data['ResolutionTableID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetDatasourceTablesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetDatasourceTablesRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Cursor`
        if (data['Cursor']) { // data not null
          APICursor.validateJSON(data['Cursor']);
        }
        // ensure the json data is a string
        if (data['NameFilter'] && !(typeof data['NameFilter'] === 'string' || data['NameFilter'] instanceof String)) {
            throw new Error("Expected the field `NameFilter` to be a primitive type in the JSON string but got " + data['NameFilter']);
        }

        return true;
    }


}



/**
 * @member {module:com.alterian.ja.model/APICursor} Cursor
 */
GetDatasourceTablesRequest.prototype['Cursor'] = undefined;

/**
 * Supply a database ID to filter the result to just the tables within this database. Ignore this parameter to fetch all tables, which can be slow.
 * @member {Number} DatabaseID
 */
GetDatasourceTablesRequest.prototype['DatabaseID'] = undefined;

/**
 * Should disabled tables be included in the output?Default false
 * @member {Boolean} IncludeDisabled
 */
GetDatasourceTablesRequest.prototype['IncludeDisabled'] = undefined;

/**
 * Should invisible tables be included in the output? Default false
 * @member {Boolean} IncludeInvisible
 */
GetDatasourceTablesRequest.prototype['IncludeInvisible'] = undefined;

/**
 * Should joined table information be included in the output? Default false, as this can be large
 * @member {Boolean} IncludeJoins
 */
GetDatasourceTablesRequest.prototype['IncludeJoins'] = undefined;

/**
 * Should linked table information be included in the output? Default false, as this can be large
 * @member {Boolean} IncludeLinks
 */
GetDatasourceTablesRequest.prototype['IncludeLinks'] = undefined;

/**
 * Exclude attributes, etc. from the results
 * @member {Boolean} MinimalResults
 */
GetDatasourceTablesRequest.prototype['MinimalResults'] = undefined;

/**
 * Optionally filter on the name
 * @member {String} NameFilter
 */
GetDatasourceTablesRequest.prototype['NameFilter'] = undefined;

/**
 * Optionally filter to include only those results that can be directly resolved to the specified table (i.e those that are 1:1 or *:1 joined such that there is a maximum of one linked candidate row per resolution row
 * @member {Number} ResolutionTableID
 */
GetDatasourceTablesRequest.prototype['ResolutionTableID'] = undefined;






export default GetDatasourceTablesRequest;

