/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetEventStreamRequest model module.
 * @module com.alterian.ja.model/GetEventStreamRequest
 * @version 6.35.0
 */
class GetEventStreamRequest {
    /**
     * Constructs a new <code>GetEventStreamRequest</code>.
     * @alias module:com.alterian.ja.model/GetEventStreamRequest
     */
    constructor() { 
        
        GetEventStreamRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetEventStreamRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/GetEventStreamRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/GetEventStreamRequest} The populated <code>GetEventStreamRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetEventStreamRequest();

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetEventStreamRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetEventStreamRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Id of the event stream you would like to see
 * @member {Number} Id
 */
GetEventStreamRequest.prototype['Id'] = undefined;






export default GetEventStreamRequest;

