/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OpportunityItemType from './OpportunityItemType';

/**
 * The OpportunityItem model module.
 * @module com.alterian.ja.model/OpportunityItem
 * @version 6.35.0
 */
class OpportunityItem {
    /**
     * Constructs a new <code>OpportunityItem</code>.
     * Abstract base class to define the essential properties that make up an OpportuntiyItem
     * @alias module:com.alterian.ja.model/OpportunityItem
     */
    constructor() { 
        
        OpportunityItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OpportunityItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/OpportunityItem} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/OpportunityItem} The populated <code>OpportunityItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpportunityItem();

            if (data.hasOwnProperty('OpportunityId')) {
                obj['OpportunityId'] = ApiClient.convertToType(data['OpportunityId'], 'Number');
            }
            if (data.hasOwnProperty('Type')) {
                obj['Type'] = OpportunityItemType.constructFromObject(data['Type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OpportunityItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OpportunityItem</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * ID of the Opportuntiy it relates to
 * @member {Number} OpportunityId
 */
OpportunityItem.prototype['OpportunityId'] = undefined;

/**
 * @member {module:com.alterian.ja.model/OpportunityItemType} Type
 */
OpportunityItem.prototype['Type'] = undefined;






export default OpportunityItem;

