/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PatternTaskType from './PatternTaskType';

/**
 * The RequestCancelPatternTasksRequest model module.
 * @module com.alterian.ja.model/RequestCancelPatternTasksRequest
 * @version 6.35.0
 */
class RequestCancelPatternTasksRequest {
    /**
     * Constructs a new <code>RequestCancelPatternTasksRequest</code>.
     * @alias module:com.alterian.ja.model/RequestCancelPatternTasksRequest
     */
    constructor() { 
        
        RequestCancelPatternTasksRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestCancelPatternTasksRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/RequestCancelPatternTasksRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/RequestCancelPatternTasksRequest} The populated <code>RequestCancelPatternTasksRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestCancelPatternTasksRequest();

            if (data.hasOwnProperty('PatternId')) {
                obj['PatternId'] = ApiClient.convertToType(data['PatternId'], 'Number');
            }
            if (data.hasOwnProperty('TaskTypes')) {
                obj['TaskTypes'] = ApiClient.convertToType(data['TaskTypes'], [PatternTaskType]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequestCancelPatternTasksRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequestCancelPatternTasksRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['TaskTypes'])) {
            throw new Error("Expected the field `TaskTypes` to be an array in the JSON data but got " + data['TaskTypes']);
        }

        return true;
    }


}



/**
 * Pattern Id
 * @member {Number} PatternId
 */
RequestCancelPatternTasksRequest.prototype['PatternId'] = undefined;

/**
 * Task types to cancel (defaults to all)
 * @member {Array.<module:com.alterian.ja.model/PatternTaskType>} TaskTypes
 */
RequestCancelPatternTasksRequest.prototype['TaskTypes'] = undefined;






export default RequestCancelPatternTasksRequest;

