/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SearchPredicates.
* @enum {}
* @readonly
*/
export default class SearchPredicates {
    
        /**
         * value: 1
         * @const
         */
        "NAME" = 1;

    

    /**
    * Returns a <code>SearchPredicates</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.alterian.ja.model/SearchPredicates} The enum <code>SearchPredicates</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

