/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetLoginBrandDefaultRequest model module.
 * @module com.alterian.ja.model/SetLoginBrandDefaultRequest
 * @version 6.35.0
 */
class SetLoginBrandDefaultRequest {
    /**
     * Constructs a new <code>SetLoginBrandDefaultRequest</code>.
     * @alias module:com.alterian.ja.model/SetLoginBrandDefaultRequest
     */
    constructor() { 
        
        SetLoginBrandDefaultRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetLoginBrandDefaultRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/SetLoginBrandDefaultRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/SetLoginBrandDefaultRequest} The populated <code>SetLoginBrandDefaultRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetLoginBrandDefaultRequest();

            if (data.hasOwnProperty('BrandId')) {
                obj['BrandId'] = ApiClient.convertToType(data['BrandId'], 'Number');
            }
            if (data.hasOwnProperty('LoginId')) {
                obj['LoginId'] = ApiClient.convertToType(data['LoginId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SetLoginBrandDefaultRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SetLoginBrandDefaultRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['LoginId'] && !(typeof data['LoginId'] === 'string' || data['LoginId'] instanceof String)) {
            throw new Error("Expected the field `LoginId` to be a primitive type in the JSON string but got " + data['LoginId']);
        }

        return true;
    }


}



/**
 * Brand you would like to default this login to for authentication purposes
 * @member {Number} BrandId
 */
SetLoginBrandDefaultRequest.prototype['BrandId'] = undefined;

/**
 * The login you would like to set; provide no value and it will use the token to get the login id (current login)
 * @member {String} LoginId
 */
SetLoginBrandDefaultRequest.prototype['LoginId'] = undefined;






export default SetLoginBrandDefaultRequest;

