/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SettingAppliesTo from './SettingAppliesTo';

/**
 * The SettingValue model module.
 * @module com.alterian.ja.model/SettingValue
 * @version 6.35.0
 */
class SettingValue {
    /**
     * Constructs a new <code>SettingValue</code>.
     * 
     * @alias module:com.alterian.ja.model/SettingValue
     */
    constructor() { 
        
        SettingValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SettingValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/SettingValue} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/SettingValue} The populated <code>SettingValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettingValue();

            if (data.hasOwnProperty('SettingId')) {
                obj['SettingId'] = ApiClient.convertToType(data['SettingId'], 'Number');
            }
            if (data.hasOwnProperty('SiteId')) {
                obj['SiteId'] = ApiClient.convertToType(data['SiteId'], 'Number');
            }
            if (data.hasOwnProperty('Source')) {
                obj['Source'] = SettingAppliesTo.constructFromObject(data['Source']);
            }
            if (data.hasOwnProperty('Value')) {
                obj['Value'] = ApiClient.convertToType(data['Value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SettingValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SettingValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['Value'] && !(typeof data['Value'] === 'string' || data['Value'] instanceof String)) {
            throw new Error("Expected the field `Value` to be a primitive type in the JSON string but got " + data['Value']);
        }

        return true;
    }


}



/**
 * 
 * @member {Number} SettingId
 */
SettingValue.prototype['SettingId'] = undefined;

/**
 * 
 * @member {Number} SiteId
 */
SettingValue.prototype['SiteId'] = undefined;

/**
 * @member {module:com.alterian.ja.model/SettingAppliesTo} Source
 */
SettingValue.prototype['Source'] = undefined;

/**
 * 
 * @member {String} Value
 */
SettingValue.prototype['Value'] = undefined;






export default SettingValue;

