/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceType from './ResourceType';

/**
 * The TakeOwnershipPermissionRequest model module.
 * @module com.alterian.ja.model/TakeOwnershipPermissionRequest
 * @version 6.35.0
 */
class TakeOwnershipPermissionRequest {
    /**
     * Constructs a new <code>TakeOwnershipPermissionRequest</code>.
     * @alias module:com.alterian.ja.model/TakeOwnershipPermissionRequest
     */
    constructor() { 
        
        TakeOwnershipPermissionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TakeOwnershipPermissionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/TakeOwnershipPermissionRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/TakeOwnershipPermissionRequest} The populated <code>TakeOwnershipPermissionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TakeOwnershipPermissionRequest();

            if (data.hasOwnProperty('ItemID')) {
                obj['ItemID'] = ApiClient.convertToType(data['ItemID'], 'Number');
            }
            if (data.hasOwnProperty('ItemType')) {
                obj['ItemType'] = ResourceType.constructFromObject(data['ItemType']);
            }
            if (data.hasOwnProperty('NewOwnerID')) {
                obj['NewOwnerID'] = ApiClient.convertToType(data['NewOwnerID'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TakeOwnershipPermissionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TakeOwnershipPermissionRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Item to take ownership of
 * @member {Number} ItemID
 */
TakeOwnershipPermissionRequest.prototype['ItemID'] = undefined;

/**
 * @member {module:com.alterian.ja.model/ResourceType} ItemType
 */
TakeOwnershipPermissionRequest.prototype['ItemType'] = undefined;

/**
 * ID of the new owner
 * @member {Number} NewOwnerID
 */
TakeOwnershipPermissionRequest.prototype['NewOwnerID'] = undefined;






export default TakeOwnershipPermissionRequest;

