/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateChannelRequest model module.
 * @module com.alterian.ja.model/UpdateChannelRequest
 * @version 6.35.0
 */
class UpdateChannelRequest {
    /**
     * Constructs a new <code>UpdateChannelRequest</code>.
     * @alias module:com.alterian.ja.model/UpdateChannelRequest
     */
    constructor() { 
        
        UpdateChannelRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateChannelRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.alterian.ja.model/UpdateChannelRequest} obj Optional instance to populate.
     * @return {module:com.alterian.ja.model/UpdateChannelRequest} The populated <code>UpdateChannelRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateChannelRequest();

            if (data.hasOwnProperty('HexColour')) {
                obj['HexColour'] = ApiClient.convertToType(data['HexColour'], 'String');
            }
            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateChannelRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateChannelRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['HexColour'] && !(typeof data['HexColour'] === 'string' || data['HexColour'] instanceof String)) {
            throw new Error("Expected the field `HexColour` to be a primitive type in the JSON string but got " + data['HexColour']);
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }

        return true;
    }


}



/**
 * Hex colour for the channel mapping, for instance #FF0000 is red
 * @member {String} HexColour
 */
UpdateChannelRequest.prototype['HexColour'] = undefined;

/**
 * Id of the @see(EventStreamChannel) to uupdate; obtained by calling @see(GetChannels)
 * @member {Number} Id
 */
UpdateChannelRequest.prototype['Id'] = undefined;

/**
 * Name of the channel
 * @member {String} Name
 */
UpdateChannelRequest.prototype['Name'] = undefined;






export default UpdateChannelRequest;

