/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyAnalyticsApi);
  }
}(this, function(expect, JourneyAnalyticsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyAnalyticsApi.DMClientSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DMClientSettings', function() {
    it('should create an instance of DMClientSettings', function() {
      // uncomment below and update the code to test DMClientSettings
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be.a(JourneyAnalyticsApi.DMClientSettings);
    });

    it('should have the property inboundDomain (base name: "InboundDomain")', function() {
      // uncomment below and update the code to test the property inboundDomain
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property contentDomain (base name: "ContentDomain")', function() {
      // uncomment below and update the code to test the property contentDomain
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property uploadImageDefault (base name: "UploadImageDefault")', function() {
      // uncomment below and update the code to test the property uploadImageDefault
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property dMWCMList (base name: "DMWCMList")', function() {
      // uncomment below and update the code to test the property dMWCMList
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property PVID (base name: "PVID")', function() {
      // uncomment below and update the code to test the property PVID
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property userCulture (base name: "UserCulture")', function() {
      // uncomment below and update the code to test the property userCulture
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property omnitureSettings (base name: "OmnitureSettings")', function() {
      // uncomment below and update the code to test the property omnitureSettings
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property defaultTemplateCodePage (base name: "DefaultTemplateCodePage")', function() {
      // uncomment below and update the code to test the property defaultTemplateCodePage
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property pVUrl (base name: "PVUrl")', function() {
      // uncomment below and update the code to test the property pVUrl
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

    it('should have the property sM2Url (base name: "SM2Url")', function() {
      // uncomment below and update the code to test the property sM2Url
      //var instance = new JourneyAnalyticsApi.DMClientSettings();
      //expect(instance).to.be();
    });

  });

}));
