/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyAnalyticsApi);
  }
}(this, function(expect, JourneyAnalyticsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyAnalyticsApi.DMClient();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DMClient', function() {
    it('should create an instance of DMClient', function() {
      // uncomment below and update the code to test DMClient
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be.a(JourneyAnalyticsApi.DMClient);
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property virtualMTA (base name: "VirtualMTA")', function() {
      // uncomment below and update the code to test the property virtualMTA
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property connectionString (base name: "ConnectionString")', function() {
      // uncomment below and update the code to test the property connectionString
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property hashTable (base name: "HashTable")', function() {
      // uncomment below and update the code to test the property hashTable
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property contentPath (base name: "ContentPath")', function() {
      // uncomment below and update the code to test the property contentPath
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property contentURL (base name: "ContentURL")', function() {
      // uncomment below and update the code to test the property contentURL
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property seats (base name: "Seats")', function() {
      // uncomment below and update the code to test the property seats
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property setID (base name: "SetID")', function() {
      // uncomment below and update the code to test the property setID
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "Icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property contentServerID (base name: "ContentServerID")', function() {
      // uncomment below and update the code to test the property contentServerID
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property directory (base name: "Directory")', function() {
      // uncomment below and update the code to test the property directory
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property dBServerID (base name: "DBServerID")', function() {
      // uncomment below and update the code to test the property dBServerID
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property dBName (base name: "DBName")', function() {
      // uncomment below and update the code to test the property dBName
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property mTAServerID (base name: "MTAServerID")', function() {
      // uncomment below and update the code to test the property mTAServerID
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property defaultDC (base name: "DefaultDC")', function() {
      // uncomment below and update the code to test the property defaultDC
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property deliveryContexts (base name: "DeliveryContexts")', function() {
      // uncomment below and update the code to test the property deliveryContexts
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "Settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

    it('should have the property imageBasePath (base name: "ImageBasePath")', function() {
      // uncomment below and update the code to test the property imageBasePath
      //var instance = new JourneyAnalyticsApi.DMClient();
      //expect(instance).to.be();
    });

  });

}));
