/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyAnalyticsApi);
  }
}(this, function(expect, JourneyAnalyticsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyAnalyticsApi.EventStreamTransition();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventStreamTransition', function() {
    it('should create an instance of EventStreamTransition', function() {
      // uncomment below and update the code to test EventStreamTransition
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be.a(JourneyAnalyticsApi.EventStreamTransition);
    });

    it('should have the property interaction (base name: "Interaction")', function() {
      // uncomment below and update the code to test the property interaction
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "From")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "To")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

    it('should have the property secondaryFrom (base name: "SecondaryFrom")', function() {
      // uncomment below and update the code to test the property secondaryFrom
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

    it('should have the property secondaryTo (base name: "SecondaryTo")', function() {
      // uncomment below and update the code to test the property secondaryTo
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "Count")', function() {
      // uncomment below and update the code to test the property count
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

    it('should have the property isPrediction (base name: "IsPrediction")', function() {
      // uncomment below and update the code to test the property isPrediction
      //var instance = new JourneyAnalyticsApi.EventStreamTransition();
      //expect(instance).to.be();
    });

  });

}));
