/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyAnalyticsApi);
  }
}(this, function(expect, JourneyAnalyticsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RunSequencePredictorRequest', function() {
    it('should create an instance of RunSequencePredictorRequest', function() {
      // uncomment below and update the code to test RunSequencePredictorRequest
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be.a(JourneyAnalyticsApi.RunSequencePredictorRequest);
    });

    it('should have the property eventStreamId (base name: "EventStreamId")', function() {
      // uncomment below and update the code to test the property eventStreamId
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property isPublic (base name: "IsPublic")', function() {
      // uncomment below and update the code to test the property isPublic
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property isSynchronous (base name: "IsSynchronous")', function() {
      // uncomment below and update the code to test the property isSynchronous
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property modelId (base name: "ModelId")', function() {
      // uncomment below and update the code to test the property modelId
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property predictionOptions (base name: "PredictionOptions")', function() {
      // uncomment below and update the code to test the property predictionOptions
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property predictionSnapshotOptions (base name: "PredictionSnapshotOptions")', function() {
      // uncomment below and update the code to test the property predictionSnapshotOptions
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property trainingOptions (base name: "TrainingOptions")', function() {
      // uncomment below and update the code to test the property trainingOptions
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

    it('should have the property trainingSnapshotOptions (base name: "TrainingSnapshotOptions")', function() {
      // uncomment below and update the code to test the property trainingSnapshotOptions
      //var instance = new JourneyAnalyticsApi.RunSequencePredictorRequest();
      //expect(instance).to.be();
    });

  });

}));
