/**
 * Journey Analytics API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.35.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.JourneyAnalyticsApi);
  }
}(this, function(expect, JourneyAnalyticsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SequencePredictorTrainingOptions', function() {
    it('should create an instance of SequencePredictorTrainingOptions', function() {
      // uncomment below and update the code to test SequencePredictorTrainingOptions
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be.a(JourneyAnalyticsApi.SequencePredictorTrainingOptions);
    });

    it('should have the property modelName (base name: "ModelName")', function() {
      // uncomment below and update the code to test the property modelName
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property trainingRatio (base name: "TrainingRatio")', function() {
      // uncomment below and update the code to test the property trainingRatio
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property encodingPadMode (base name: "EncodingPadMode")', function() {
      // uncomment below and update the code to test the property encodingPadMode
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property randomSeed (base name: "RandomSeed")', function() {
      // uncomment below and update the code to test the property randomSeed
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property embeddingLayerSize (base name: "EmbeddingLayerSize")', function() {
      // uncomment below and update the code to test the property embeddingLayerSize
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property lstmLayerSize (base name: "LstmLayerSize")', function() {
      // uncomment below and update the code to test the property lstmLayerSize
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property numberOfEpochs (base name: "NumberOfEpochs")', function() {
      // uncomment below and update the code to test the property numberOfEpochs
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property batchSize (base name: "BatchSize")', function() {
      // uncomment below and update the code to test the property batchSize
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property categoricalFeatures (base name: "CategoricalFeatures")', function() {
      // uncomment below and update the code to test the property categoricalFeatures
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property isDataDebugRequired (base name: "IsDataDebugRequired")', function() {
      // uncomment below and update the code to test the property isDataDebugRequired
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

    it('should have the property isCombineCategoriesRequired (base name: "IsCombineCategoriesRequired")', function() {
      // uncomment below and update the code to test the property isCombineCategoriesRequired
      //var instance = new JourneyAnalyticsApi.SequencePredictorTrainingOptions();
      //expect(instance).to.be();
    });

  });

}));
